FROM python
ENV PYTHONUNBUFFERED=1

WORKDIR /src

# pipを使ってpoetryをインストール
RUN pip install poetry

# poetryの定義ファイルをコピー (存在する場合)
COPY pyproject.toml* poetry.lock* ./

# サービスアカウントキーをコピー
COPY serviceAccountKey.json /src/serviceAccountKey.json

# poetryでライブラリをインストール (pyproject.tomlが既にある場合)
RUN poetry config virtualenvs.in-project true
RUN if [ -f pyproject.toml ]; then poetry install --no-root; fi

# そのほかの大事なあまり手を加えないファイルをコピーする
COPY alembic ./alembic
COPY alembic.ini ./
COPY entrypoint.sh ./


# uvicornのサーバーを立ち上げる
# ENTRYPOINT ["poetry", "run", "uvicorn", "api.main:app", "--host", "0.0.0.0", "--reload"]
# CMD ["bash"]
# RUN poetry run uvicorn api.main:app --host 0.0.0.0 --reload\
# && poetry run alembic revision --autogenerate -m "Initial migration"\
# && poetry run alembic upgrade head\
# && poetry run python -m api.database.seed
# マイグレーションのスクリプトを実行
# RUN poetry run alembic revision --autogenerate -m "Initial migration"
# RUN poetry run alembic upgrade head
# シーディングのスクリプトを実行
# RUN poetry run python -m api.database.seed