FROM python
ENV PYTHONUNBUFFERED=1

WORKDIR /src

# pipを使ってpoetryをインストール
RUN pip install poetry

# poetryの定義ファイルをコピー (存在する場合)
COPY pyproject.toml* poetry.lock* ./

# サービスアカウントキーをコピー
COPY serviceAccountKey.json /src/serviceAccountKey.json

# poetryでライブラリをインストール (pyproject.tomlが既にある場合)
RUN poetry config virtualenvs.in-project true
RUN if [ -f pyproject.toml ]; then poetry install --no-root; fi

# そのほかの大事なあまり手を加えないファイルをコピーする
COPY alembic ./alembic
COPY alembic.ini ./
COPY logging.yaml ./logging.yaml
#COPY entrypoint.sh ./
