version: '3'
services:
  backend:
    build: .
    volumes:
      - ./api:/src/api
      - ./.dockervenv:/src/.venv:rw
    tty: true
    ports:
      - 8000:8000  # ホストマシンのポート8000を、docker内のポート8000に接続する